// demo/vue/src/App.vue
<template>
  <div id="app">
    <h1>AI Stock View Chart Vue Demo</h1>
    <div id="chartContainer" class="chart-container"></div>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import { generateCandlestickData } from '../../../dist/indicators/demo.js'

export default {
  name: 'App',
  setup() {
    const chartContainer = ref(null)
    import ('../../../dist/indicators/demo.js')

    onMounted(() => {
      // Import the stock chart library
      import('../../../dist/stock-chart.js').then((module) => {
        const StockChart = module.default
        
        // Sample data
        const data = generateCandlestickData(500)

        StockChart.init('chartContainer', {
          theme: 'light',
          chartName: {
            name: 'Test Vue',
            code: 'vue'
          },
          initialVisibleCandles: 100,
          plots: [
            {
              id: 'main',
              type: 'candlestick',
              data: data,
              heightRatio: 1
            }
          ]
          
        })
      })
    })

    return {
      chartContainer
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.chart-container {
  width: 100%;
  height: 600px;
  margin: 20px auto;
  max-width: 1200px;
}
</style>

// demo/react/src/App.jsx
import React, { useEffect, useRef } from 'react';
import { generateCandlestickData } from '../../../dist/indicators/demo.min.js';

function App() {
  const chartContainerRef = useRef(null);

  useEffect(() => {
    const loadChart = async () => {
      try {
        // Generate sample data using the same function as Vue demo
        const data = generateCandlestickData(500);

        // Import the chart dynamically
        const { default: StockChart } = await import('../../../dist/stock-chart.min.js');
        
        // Initialize chart using the ref's DOM element
        if (chartContainerRef.current) {
          StockChart.init('chart-container', {
            theme: 'light',
            chartName: {
              name: 'Test React AI Stock View chart',
              code: 'ASV chart'
            },
            initialVisibleCandles: 100,
            plots: [
              {
                id: 'main',
                type: 'candlestick',
                data: data,
                heightRatio: 1
              }
            ]
          });
        }
      } catch (error) {
        console.error('Error loading stock chart:', error);
      }
    }

    loadChart();
  }, []);

  return (
    <div className="App">
      <h1>Stock Chart React Demo</h1>
      <div ref={chartContainerRef} id="chart-container" className="chart-container"></div>
    </div>
  );
}

export default App;
